### ISSUE TITLE
Why don't you just used DNN model to estimate noise PSD instead of using conventional noise estimation method?

### ISSUE THREAD

**Issue by hylee-250** [CARNIVAL-IITP/Noise_suppression#2]
Why don't you just used DNN model to estimate noise PSD instead of using conventional noise estimation method?

**Comment by roar27** [comment]
Personally, I estimated noise with a DNN model, but the performance was not as good as that of a conventional noise estimation model, and I thought it was advantageous to use a conventional noise estimation model in terms of model size and computation.
